FROM alpine:3.7
MAINTAINER Zengs.<zingsono@gmail.com>
LABEL name="alpine" version="3.7" description="Custom image . alpine"

RUN apk update && apk add curl bash tree tzdata && cp -r -f /usr/share/zoneinfo/Hongkong /etc/localtime


