# https://hub.docker.com/_/nginx/
# https://github.com/nginxinc/docker-nginx/blob/d377983a14b214fcae4b8e34357761282aca788f/stable/alpine/Dockerfile
FROM nginx:1.14.0-alpine

# 端口：80
# 配置文件：/etc/nginx/
# 数据目录：/usr/share/nginx/html/

# 修改配置与数据目录在
