FROM mongo:4.2
# 4.2-rc  https://github.com/docker-library/mongo/blob/e94cbf806caabc1fc46bd50af8ae74347f2b1cf8/4.2-rc/Dockerfile
# 4.2     https://github.com/docker-library/mongo/blob/2f757af6d12f4239cf5541455b011921ee4c06d1/4.2/Dockerfile

# 设置时区
RUN cp /usr/share/zoneinfo/Asia/Shanghai  /etc/localtime
