FROM centos:6.9

MAINTAINER Zengs. <zingsono@gmail.com>

RUN yum -y install iproute nmap wget tar unzip



RUN mkdir /opt/mongodb && wget https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.6.1.tgz

CMD ["/bin/bash"]
