FROM alpine:3.10
MAINTAINER Zengs.<zingsono@gmail.com>
# RUN apk update && apk add curl bash tree tzdata && cp -r -f /usr/share/zoneinfo/Hongkong /etc/localtime
RUN cp -r -f /usr/share/zoneinfo/Hongkong /etc/localtime

