FROM zingsono/centos:7
MAINTAINER Zengs.<zingsono@gmail.com>
# JRE 1.8.0

# OpenJDK Runtime Environment (build 1.8.0_171-b10)
RUN yum install -y java-1.8.0-openjdk.x86_64 && yum clean all

ENV JRE_HOME=/usr/lib/jvm/jre-1.8.0
ENV JAVA_HOME=/usr/lib/jvm/jre-1.8.0
